# Generated by Django 3.2 on 2021-05-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('alive_or_not', models.CharField(choices=[('YES', ' YES'), ('NO', 'NO')], default='YES', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=235)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('genre', models.CharField(choices=[('FANTASY', 'FANTASY'), ('ADVENTURE', 'ADVENTURE'), ('COMEDY', 'COMEDY'), ('HORROR', 'HORROR'), ('DRAMA', 'DRAMA'), ('SACRED', 'SACRED'), ('NO', 'NO')], default='NO', max_length=200)),
                ('rating', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='django_books.author')),
            ],
        ),
    ]
